import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { Providers } from '@/redux/Provider'
import { ThemeProvider } from '@/components/ThemeProvider'
import NextAuthProvider from '@/components/NextAuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children, authModal, session }) {
    return (
        <html lang="en" className={inter.className}>
            <body className="min-h-screen pt-12">
                <NextAuthProvider>
                    <Providers>
                        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
                            <Navbar />
                            {authModal}
                            <div className="container max-w-7xl mx-auto h-full pt-14">{children}</div>
                        </ThemeProvider>
                    </Providers>
                </NextAuthProvider>
            </body>
        </html>
    )
}
