import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/components/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children, authModal }) {
    return (
        <html lang="en" className={inter.className}>
            <body className="min-h-screen pt-12">
                <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
                    <Navbar />
                    {authModal}
                    <div className="container max-w-7xl mx-auto h-full pt-12">{children}</div>
                </ThemeProvider>
            </body>
        </html>
    )
}
